apiVersion: v1
kind: Service
metadata:
  name: nginx # 이름이 정확해야함. 다른 곳에서 이 이름을 참조하고 있음.
spec: # 타입은 기본적으로 ClusterIP를 사용하게 됌.
  selector:
    app: nginx
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
